"""SRE Agent Tools for GCP Cloud Logging analysis and Incident Report generation."""

import json
import os
from typing import Any

from app.log_parser import classify_log_event, parse_gcp_logs


def parse_and_classify_gcp_logs(log_source: str) -> str:
    """Parses raw GCP Cloud Logging logs and classifies every event by severity.

    Args:
        log_source: A JSON string containing GCP LogEntry objects, a file path
          pointing to a log file, or raw text logs.

    Returns:
        A JSON string containing the count of CRITICAL, WARNING, and INFO
        events, list of classified events, affected GCP resources, and trace
        correlations.
    """
    entries = parse_gcp_logs(log_source)
    if not entries:
        return json.dumps({"error": "No valid log entries found in input."})

    classified_events = []
    severity_counts = {"CRITICAL": 0, "WARNING": 0, "INFO": 0}
    affected_resources = set()
    trace_map: dict[str, list[dict[str, Any]]] = {}

    for entry in entries:
        classified = classify_log_event(entry)
        sev = classified["classified_severity"]
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

        res = f"{classified['resource_type']}"
        if classified.get("resource_labels"):
            res += f" ({json.dumps(classified['resource_labels'])})"
        affected_resources.add(res)

        trace = classified.get("trace")
        if trace:
            if trace not in trace_map:
                trace_map[trace] = []
            trace_map[trace].append(classified)

        classified_events.append(classified)

    summary_result = {
        "total_log_entries": len(classified_events),
        "severity_summary": severity_counts,
        "affected_resources": list(affected_resources),
        "traces_analyzed": len(trace_map),
        "critical_events": [e for e in classified_events if e["classified_severity"] == "CRITICAL"],
        "warning_events": [e for e in classified_events if e["classified_severity"] == "WARNING"],
        "info_events": [e for e in classified_events if e["classified_severity"] == "INFO"],
        "classified_events": classified_events,
    }

    return json.dumps(summary_result, indent=2)


def load_sample_log_dataset(dataset_name: str) -> str:
    """Loads a pre-bundled sample GCP Cloud Logging dataset.

    Args:
        dataset_name: Name of sample dataset ('outage' or 'gcp_cloud_logging_outage').

    Returns:
        The raw JSON contents of the sample log file.
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sample_file = os.path.join(base_dir, "sample_logs", "gcp_cloud_logging_outage.json")

    if os.path.exists(sample_file):
        with open(sample_file, encoding="utf-8") as f:
            return f.read()

    return json.dumps({"error": f"Sample dataset '{dataset_name}' not found at {sample_file}."})


def format_incident_report(
    executive_summary: str,
    incident_severity: str,
    timeline_and_impact: str,
    rca_analysis: str,
    recommended_actions: str,
) -> str:
    """Formats the SRE analysis into a standardized Markdown Incident Report.

    Args:
        executive_summary: High-level executive overview of what happened.
        incident_severity: Overall incident severity rating (e.g. CRITICAL, HIGH, MEDIUM, LOW).
        timeline_and_impact: Chronological sequence of events and impacted GCP services.
        rca_analysis: Root Cause Analysis explaining primary cause and cascading failures.
        recommended_actions: Actionable remediation steps (Immediate Mitigations & Long-term SRE Preventive Actions).

    Returns:
        A Markdown-formatted Incident Report.
    """
    report = f"""# 🚨 SRE Incident Report

**Overall Incident Severity**: `{incident_severity.upper()}`

---

## 📌 Executive Summary
{executive_summary}

---

## ⏱️ Timeline & Service Impact
{timeline_and_impact}

---

## 🔍 Root Cause Analysis (RCA)
{rca_analysis}

---

## 🛠️ Recommended Action Items

### Immediate Mitigations (P0/P1)
{recommended_actions}

---
*Report generated by GCP SRE Agent using Google ADK & agents-cli.*
"""
    return report
