# Agent Gateway egress governance and the Agent Registry entries it allows.
# Custom file (not generated by agents-cli).
#
# Prerequisite: the engine must run as an Agent Identity (service.tf). The gateway
# itself is bound at deploy time (`agents-cli deploy --agent-gateway-egress`), see
# .github/actions/deploy-agent.

locals {
  # Every Agent Identity of Agent Runtime engines in this project
  agent_identity_principal_set = "principalSet://agents.global.proj-${data.google_project.project.number}.system.id.goog/attribute.platformContainer/aiplatform/projects/${data.google_project.project.number}"

  # Last segment of projects/*/locations/*/reasoningEngines/<id>
  engine_id = element(split("/", google_vertex_ai_reasoning_engine.app.name), length(split("/", google_vertex_ai_reasoning_engine.app.name)) - 1)
}

# The runtime roles the agent had as a service account now belong to its Agent Identity
resource "google_project_iam_member" "agent_identity_roles" {
  for_each = toset(var.app_sa_roles)

  project    = var.project_id
  role       = each.value
  member     = local.agent_identity_principal_set
  depends_on = [google_project_service.services]
}

# Governs what the agents bound to it may call. Access is granted by IAP
# policies on the destinations' Agent Registry entries (mcp_server_iap_policy).
resource "google_network_services_agent_gateway" "egress" {
  provider = google-beta
  project  = var.project_id
  name     = "${var.project_name}-egress-gateway"
  location = var.region

  google_managed {
    governed_access_path = "AGENT_TO_ANYWHERE"
  }

  registries = [
    "//agentregistry.googleapis.com/projects/${data.google_project.project.number}/locations/${var.region}",
  ]

  depends_on = [google_project_service.services]
}

# The hosts every Agent Runtime engine needs regardless of what it does --
# https://docs.cloud.google.com/gemini-enterprise-agent-platform/scale/runtime/agent-gateway-runtime-deploy#before-you-begin.
# Hostname matching on the gateway is exact, so the mTLS/regional variants
# are each their own entry, not implied by the plain one.
locals {
  essential_endpoint_hosts = [
    "agentregistry.googleapis.com",
    "logging.googleapis.com",
    "logging.mtls.googleapis.com",
    "telemetry.googleapis.com",
    "telemetry.mtls.googleapis.com",
    "cloudtrace.googleapis.com",
    "cloudtrace.mtls.googleapis.com",
    "monitoring.googleapis.com",
    "monitoring.mtls.googleapis.com",
    "secretmanager.googleapis.com",
    "secretmanager.mtls.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "cloudresourcemanager.mtls.googleapis.com",
    "iamcredentials.googleapis.com",
    "iamcredentials.mtls.googleapis.com",
    "aiplatform.googleapis.com",
    "aiplatform.mtls.googleapis.com",
    "${var.region}-aiplatform.googleapis.com",
    "${var.region}-aiplatform.mtls.googleapis.com",
    "aiplatform.${var.region}.rep.googleapis.com",
    "storage.googleapis.com",
    "storage.mtls.googleapis.com",
  ]
}

resource "google_agent_registry_service" "essential_endpoint" {
  provider     = google-beta
  for_each     = toset(local.essential_endpoint_hosts)
  project      = var.project_id
  location     = var.region
  service_id   = "essential-${replace(each.value, ".", "-")}"
  display_name = each.value
  description  = "Essential Agent Runtime platform endpoint."

  endpoint_spec {
    type = "NO_SPEC"
  }

  interfaces {
    url              = "https://${each.value}"
    protocol_binding = "HTTP_JSON"
  }

  depends_on = [google_project_service.services]
}

# Host-level access, not per-tool: unlike mcp_server_iap_policy, none of these
# carry the MCP toolName/isReadOnly condition, so every Agent Identity gets in.
resource "google_iap_agent_registry_endpoint_iam_binding" "essential_endpoint_egress" {
  provider    = google-beta
  for_each    = google_agent_registry_service.essential_endpoint
  project     = var.project_id
  location    = var.region
  endpoint_id = element(split("/", each.value.registry_resource), length(split("/", each.value.registry_resource)) - 1)
  role        = "roles/iap.egressor"
  members     = [local.agent_identity_principal_set]
}

# Feature-specific endpoints (agent-gateway-runtime-deploy#before-you-begin):
# Sessions is a per-engine URL, not covered by the bare aiplatform host above --
# the agent uses VertexAiSessionService on every turn, so its Sessions endpoint
# (plain and mtls) is registered too.
locals {
  session_endpoint_agents = {
    sre_agent = {
      engine_id       = local.engine_id
      agent_principal = local.agent_identity_principal_set
    }
  }
}

resource "google_agent_registry_service" "sessions_endpoint" {
  provider     = google-beta
  for_each     = local.session_endpoint_agents
  project      = var.project_id
  location     = var.region
  service_id   = "sessions-${replace(each.key, "_", "-")}"
  display_name = "${each.key}-sessions"
  description  = "Per-engine Vertex AI Sessions endpoint (feature-specific, not covered by the bare aiplatform host)."

  endpoint_spec {
    type = "NO_SPEC"
  }

  interfaces {
    url              = "https://${var.region}-aiplatform.googleapis.com/v1/projects/${data.google_project.project.number}/locations/${var.region}/reasoningEngines/${each.value.engine_id}/sessions"
    protocol_binding = "HTTP_JSON"
  }

  depends_on = [google_project_service.services]
}

resource "google_agent_registry_service" "sessions_endpoint_mtls" {
  provider     = google-beta
  for_each     = local.session_endpoint_agents
  project      = var.project_id
  location     = var.region
  service_id   = "sessions-mtls-${replace(each.key, "_", "-")}"
  display_name = "${each.key}-sessions-mtls"
  description  = "Per-engine Vertex AI Sessions endpoint, mtls host (Agent Identity's mTLS auto-detection redirects here)."

  endpoint_spec {
    type = "NO_SPEC"
  }

  interfaces {
    url              = "https://${var.region}-aiplatform.mtls.googleapis.com/v1/projects/${data.google_project.project.number}/locations/${var.region}/reasoningEngines/${each.value.engine_id}/sessions"
    protocol_binding = "HTTP_JSON"
  }

  depends_on = [google_project_service.services]
}

resource "google_iap_agent_registry_endpoint_iam_binding" "sessions_endpoint_egress" {
  provider    = google-beta
  for_each    = google_agent_registry_service.sessions_endpoint
  project     = var.project_id
  location    = var.region
  endpoint_id = element(split("/", each.value.registry_resource), length(split("/", each.value.registry_resource)) - 1)
  role        = "roles/iap.egressor"
  members     = [local.session_endpoint_agents[each.key].agent_principal]
}

resource "google_iap_agent_registry_endpoint_iam_binding" "sessions_endpoint_mtls_egress" {
  provider    = google-beta
  for_each    = google_agent_registry_service.sessions_endpoint_mtls
  project     = var.project_id
  location    = var.region
  endpoint_id = element(split("/", each.value.registry_resource), length(split("/", each.value.registry_resource)) - 1)
  role        = "roles/iap.egressor"
  members     = [local.session_endpoint_agents[each.key].agent_principal]
}

# Distinct from the per-endpoint bindings above: this grants egressor on the
# Agent Registry itself (project + location, not one endpoint), which the
# gateway checks to authorize a bound agent's traffic in the first place.
resource "google_iap_agent_registry_iam_binding" "registry_egress" {
  provider = google-beta
  project  = var.project_id
  location = var.region
  role     = "roles/iap.egressor"
  members  = [local.agent_identity_principal_set]
}

resource "google_network_services_authz_extension" "iap_egress" {
  project   = var.project_id
  name      = "${var.project_name}-iap-egress-authz"
  location  = var.region
  service   = "iap.googleapis.com"
  timeout   = "1s"
  fail_open = false

  metadata = {
    iapPolicyVersion   = "V2",
    iamEnforcementMode = "DRY_RUN"
  }

  depends_on = [google_project_service.services]
}

resource "google_network_security_authz_policy" "iap_egress" {
  project        = var.project_id
  name           = "${var.project_name}-iap-egress-authz-policy"
  location       = var.region
  action         = "CUSTOM"
  policy_profile = "REQUEST_AUTHZ"

  custom_provider {
    authz_extension {
      resources = [google_network_services_authz_extension.iap_egress.id]
    }
  }

  target {
    resources = [google_network_services_agent_gateway.egress.id]
  }
  depends_on = [google_project_service.services]
}
