# GitHub Actions -> Google Cloud authentication via Workload Identity Federation.
#
# Custom file (not generated by agents-cli): adapted from the `cicd` stack of the
# agents-cli template, reduced to a single project. Kept self-contained so that
# `agents-cli scaffold upgrade` has nothing to merge.

variable "repository_owner" {
  type        = string
  description = "Owner (user or organization) of the GitHub repository allowed to deploy."
}

variable "repository_name" {
  type        = string
  description = "Name of the GitHub repository allowed to deploy."
}

variable "ci_extra_roles" {
  description = "Roles the app service account needs in addition to app_sa_roles to deploy from GitHub Actions"
  type        = list(string)
  default = [
    "roles/artifactregistry.writer",
    "roles/cloudbuild.builds.builder",
  ]
}

resource "google_project_service" "wif_services" {
  for_each = toset([
    "sts.googleapis.com",
    "iamcredentials.googleapis.com",
  ])

  project            = var.project_id
  service            = each.value
  disable_on_destroy = false

  depends_on = [google_project_service.bootstrap]
}

# GitHub workflows authenticate as the agent's own service account (app_sa), so
# it also needs the build/deploy roles on top of its runtime roles.
resource "google_project_iam_member" "app_sa_ci_roles" {
  for_each = toset(var.ci_extra_roles)

  project    = var.project_id
  role       = each.value
  member     = "serviceAccount:${google_service_account.app_sa.email}"
  depends_on = [google_project_service.services]
}

# Deploying the agent "as" app_sa requires acting as that service account
resource "google_service_account_iam_member" "app_sa_acts_as_itself" {
  service_account_id = google_service_account.app_sa.name
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:${google_service_account.app_sa.email}"
}

resource "google_iam_workload_identity_pool" "sre_agent_github_pool" {
  workload_identity_pool_id = "${var.project_name}-pool"
  project                   = var.project_id
  display_name              = "GitHub Actions Pool"
  depends_on                = [google_project_service.wif_services]
}

resource "google_iam_workload_identity_pool_provider" "sre_agent_github_provider" {
  workload_identity_pool_provider_id = "${var.project_name}-oidc"
  project                            = var.project_id
  workload_identity_pool_id          = google_iam_workload_identity_pool.sre_agent_github_pool.workload_identity_pool_id
  display_name                       = "GitHub OIDC Provider"

  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com"
  }

  attribute_mapping = {
    "google.subject"             = "assertion.sub"
    "attribute.repository"       = "assertion.repository"
    "attribute.repository_owner" = "assertion.repository_owner"
  }
  attribute_condition = "attribute.repository == '${var.repository_owner}/${var.repository_name}'"
}

# Only workflows of this repository may impersonate the app service account
resource "google_service_account_iam_member" "sre_agent_github_oidc_access" {
  service_account_id = google_service_account.app_sa.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "principalSet://iam.googleapis.com/projects/${data.google_project.project.number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.sre_agent_github_pool.workload_identity_pool_id}/attribute.repository/${var.repository_owner}/${var.repository_name}"
}
